### ISSUE TITLE
There are no tmax_over_time values.

### ISSUE THREAD

**Issue by garry0garry** [mweinelt/ha-prometheus-sensor#19]
```
sensor:
  - platform: prometheus_sensor
    url: http://localhost:9090
    queries:
      - name: in3_voltage_max
        expr: max_over_time(homeassistant_sensor_voltage_v{entity="sensor.pzem_004t_v3_in3_voltage"}[1y])
        unit_of_measurement: V
        device_class: voltage
      - name: in3_voltage_max_timestamp
        expr: tmax_over_time(homeassistant_sensor_voltage_v{entity="sensor.pzem_004t_v3_in3_voltage"}[1y])
        device_class: timestamp

```
The timestamp sensor is always `unavailable`. How to find the cause of the problem?
